Major refactor: define daemons by daemon_start/stop/restart/poll/exists functions

diff --git a/rc b/rc
--- a/rc
+++ b/rc
@@ -1,6 +1,14 @@
-#!/bin/sh
+#!/bin/busybox ash
+# shellcheck shell=dash
+# shellcheck disable=SC3057
+# ash supports string indexing just fine shellcheck!
+
 # This file is executed on boot to initialize the system and can also be run by
 # the user to start/stop daemons.
+
+# Note: Preferable to use a busybox with:
+# FEATURE_SH_STANDALONE, FEATURE_PREFER_APPLETS, FEATURE_SH_NOFORK
+# Assume busybox ash shell features and prefer builtins or nofork applets
 
 PATH="$PATH:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin" # traditonal linux paths
 PATH="$PATH:/usr/lib/systemd" # systemd libexec components normally hidden from PATH
@@ -9,25 +17,82 @@ PATH="$PATH:/run/current-system/sw/lib/systemd" # systemd libexec components in 
 
 # Fallback Configuration Values, to be able to run even with a broken, deleted
 # or outdated minirc.conf:
-DAEMONS="syslog-ng iptables alsa crond dbus wpa_supplicant dhcpcd sshd privoxy polipo acpid mpd vsftpd lighttpd ntpd haveged"
-ENABLED="@dbus"
+DAEMONS="\
+syslog-ng \
+iptables \
+alsa \
+crond \
+dbus \
+wpa_supplicant \
+dhcpcd \
+sshd \
+privoxy \
+polipo \
+acpid \
+mpd \
+vsftpd \
+lighttpd \
+ntpd \
+haveged \
+"
+
+ENABLED="\
+@dbus \
+"
+
 UDEV="auto"
 NETWORK_INTERFACE="eth0"
 WIFI_INTERFACE="wlan0"
-WAIT_POLL="0.1"
-WAIT_TRIES="50"
+WAIT_POLLRATE="0.1"
+WAIT_TRIES="30"
 read -r HOSTNAME </etc/hostname
 
-# User-definable start/stop/restart/poll functions which fall back to defaults
-custom_restart() { default_restart "$@"; }
-custom_start()   { default_start   "$@"; }
-custom_stop()    { default_stop    "$@"; }
-custom_poll()    { default_poll    "$@"; }
-# TODO: Add custom_exists and don't list daemons that don't exist on the system
+main() {
+	# handle arguments
+	case "$1" in
+	init)
+		on_boot;;
+	shutdown)
+		on_shutdown;;
+	start|stop|restart)
+		cmd="$1"
+		shift
+		for dmn in ${@:-${DAEMONS}}; do
+			daemon "${cmd}" "${dmn}"
+		done;;
+	''|list)
+		# list all daemons and their status
+		for dmn in ${DAEMONS}; do
+			daemon exists "${dmn}" || continue
+			if daemon poll "${dmn}"; then
+				echo_color 2 [X] "${dmn}"
+			else
+				echo_color 0 [ ] "${dmn}"
+			fi
+		done;;
+	--version)
+		echo minirc 1.0;;
+	*)
+		self=$(basename "$0")
+		echo "Usage: ${self} [--help] [--version] <action> [list of daemons]"
+		echo
+		echo "Actions:"
+		echo "   ${self} list               shows status of all daemons (default action)"
+		echo "   ${self} start [daemons]    starts daemons"
+		echo "   ${self} stop [daemons]     stops daemons"
+		echo "   ${self} restart [daemons]  restarts daemons";;
+	esac
+}
 
-if [ -r /etc/minirc.conf ]; then
-	source /etc/minirc.conf
-fi
+# Wait in default polling manner on a condition
+wait_on() {
+	for i in $(seq "${2:-${WAIT_TRIES}}"); do
+		${1} && return 0
+		sleep "${3:-${WAIT_POLLRATE}}"
+	done
+	echo "ERROR: Gave up waiting on condition ${1}! You should debug this to avoid wasting time in init!"
+	return 1
+}
 
 on_boot() {
 	# mount the API filesystem
@@ -55,7 +120,13 @@ on_boot() {
 
 	echo_color 3 initializing udev...
 	if [ "${UDEV}" = "auto" ]; then
-		command -v systemctl && UDEV="systemd" || { command -v udevd && UDEV="eudev" || UDEV="busybox"; }
+		if command -v systemctl >/dev/null 2>&1; then
+			UDEV="systemd"
+		elif command -v udevd >/dev/null 2>&1; then
+			UDEV="eudev"
+		else
+			UDEV="busybox"
+	fi
 	fi
 	if [ "${UDEV}" = "systemd" ]; then
 		systemd-udevd --daemon
@@ -67,6 +138,7 @@ on_boot() {
 		udevadm trigger --action=add --type=devices
 	else # use busybox mdev as fallback:
 		# TODO: hotplug might not exist. It's not a normally enabled feature anymore, CONFIG_UEVENT_HELPER enables it
+		# TODO: Address "busybox" reference, might not be in PATH
 		busybox mdev -s
 		echo /sbin/mdev > /proc/sys/kernel/hotplug
 	fi
@@ -80,18 +152,15 @@ on_boot() {
 	# start the default daemons
 	echo_color 3 starting daemons...
 	for dmn in ${ENABLED}; do
-		if [ "$(echo "${dmn}" | awk '{ s=substr($0, 1, 1); print s; }')" = '@' ]; then
-			custom_start "$(echo "${dmn}" | awk '{ s=substr($0, 2); print s; }')" &
+		if [ "${dmn:0:1}" = '@' ]; then
+			daemon start "${dmn:1}" &
 		else
-			custom_start "${dmn}"
+			daemon start "${dmn}"
 		fi
 	done
 	
 	echo_color 3 mounting rest of filesystems...
-	for i in $(seq "${WAIT_TRIES}"); do
-		mount -a && break
-		sleep "${WAIT_POLL}"
-	done
+	wait_on "mount -a"
 
 	# load /etc/minirc.local
 	if [ -x /etc/minirc.local ]; then
@@ -103,7 +172,13 @@ on_boot() {
 on_shutdown() {
 	# stop the default daemons
 	echo_color 3 stopping daemons...
-	custom_stop all
+	for dmn in ${ENABLED}; do
+		if [ "${dmn:0:1}" = '@' ]; then
+			daemon stop "${dmn:1}" &
+		else
+			daemon stop "${dmn}"
+		fi
+	done
 
 	# load minirc.local.shutdown
 	if [ -x /etc/minirc.local.shutdown ]; then
@@ -124,108 +199,153 @@ on_shutdown() {
 	umount -r /run
 }
 
-default_start() {
-	echo_color 2 starting "$1"...
-	case "$1" in
-	all)
-		for dmn in ${DAEMONS} ${ENABLED}; do
-			custom_poll "${dmn##@}" || custom_start "${dmn##@}"
-		done;;
-	alsa)
-		for i in $(seq "${WAIT_TRIES}"); do
-			[ -c /dev/snd/controlC0 ] && break
-			sleep "${WAIT_POLL}"
-		done
-		alsactl restore || alsactl --no-lock restore;;
-	bitlbee)
-		su -s /bin/sh -c 'bitlbee -F' bitlbee;;
-	dbus)
-		mkdir -p /run/dbus &&
-			dbus-uuidgen --ensure &&
-			dbus-daemon --system;;
-	iptables)
-		iptables-restore < /etc/iptables/iptables.rules;;
-	sshd)
-		eval "$(command -v sshd)";;  # sshd requires an absolute path, so grab path from command -v
-	privoxy)
-		privoxy --user privoxy.privoxy /etc/privoxy/config;;
-	polipo)
-		su -c 'polipo daemonise=true logFile="/var/log/polipo.log"' -s /bin/sh - nobody;;
-	dhcpcd)
-		if ip link | grep -Fq ${NETWORK_INTERFACE}; then :; else
-			echo_color 3 "waiting for ${NETWORK_INTERFACE} to settle..."
-			for i in $(seq "${WAIT_TRIES}"); do
-				ip link | grep -Fq ${NETWORK_INTERFACE} && break
-				sleep "${WAIT_POLL}"
-			done
-		fi
-		dhcpcd -nqb;;
-	vsftpd)
-		vsftpd &;;
-	lighttpd)
-		lighttpd -f /etc/lighttpd/lighttpd.conf;;
-	ntpd)
-		ntpd -g -u ntp;;
-	wpa_supplicant)
-		for i in $(seq "${WAIT_TRIES}"); do
-			iwconfig ${WIFI_INTERFACE} && break
-			sleep "${WAIT_POLL}"
-		done
-		wpa_supplicant -Dwext -B -i"${WIFI_INTERFACE}" -c/etc/wpa_supplicant.conf;;
-	icecast)
-		icecast -b -c /etc/icecast.xml;;
-	*)
-		# fallback: start the command
-		"$1";;
+# daemon [start/stop/restart/poll/exists] service_name
+daemon() {
+	case "${1}" in
+		start)
+			echo_color 2 starting "$1"...
+			;;
+		stop)
+			echo_color 1 stopping "$1"...
+			;;
+		restart)
+			;;
+		poll)
+			;;
+		exists)
+			;;
 	esac
+	
+	if command -v "${2}"_"${1}" >/dev/null 2>&1; then
+		"${2}"_"${1}"
+	else
+		default_"${1}" "${2}"
+	fi
+}
+
+default_start() {
+	"${1}"
 }
 
 default_stop() {
-	echo_color 1 stopping "$1"...
-	case "$1" in
-	all)
-		for dmn in ${DAEMONS} ${ENABLED}; do
-			custom_poll "${dmn##@}" && custom_stop "${dmn##@}"
-		done;;
-	alsa)
-		alsactl store || alsactl --no-lock store;;
-	dbus)
-		killall dbus-launch
-		killall dbus-daemon
-		rm /run/dbus/pid;;
-	iptables)
-		for table in $(cat /proc/net/ip_tables_names); do
-			iptables-restore < /var/lib/iptables/empty-"$table".rules
-		done;;
-	*)
-		# fallback: kill all processes with the name of the command
-		killall "$1";;
-	esac
+	killall "${1}"
 }
 
 default_restart() {
-	case "$1" in
-	sshd)
-		# Make sure minirc doesn't hang up when restarting it remotely
-		busybox setsid sh -c '"$0" stop "$@"; "$0" start "$@"' "$0" "$@";;
-	*)
-		custom_stop "$@"
-		custom_start "$@";;
-	esac
+	daemon stop "${1}"
+	daemon start "${1}"
 }
 
 default_poll() {
-	case "$1" in
-	alsa)
-		return 0;;  # doesn't make much sense for this service
-	iptables)
-		iptables -L -n | grep -m 1 -q '^ACCEPT\|^REJECT';;
-	dbus)
-		test -e /run/dbus/pid;;
-	*)
-		# fallback: check if any processes of that name are running
-		pgrep "(^|/)$1\$" >/dev/null 2>&1;;
-	esac
+	pgrep "(^|/)${1}\$" >/dev/null 2>&1
+}
+
+default_exists() {
+	command -v "${1}" >/dev/null 2>&1
+}
+
+alsa_start() {
+	if wait_on "[ -c /dev/snd/controlC0 ]"; then
+		alsactl -q restore || alsactl -q --no-lock restore
+		return
+	fi
+	return 0
+}
+
+alsa_stop() {
+	mkdir -p /var/lib/alsa
+	alsactl -q store || alsactl -q --no-lock store
+}
+
+alsa_poll() {
+	return 1
+}
+
+alsa_exists() {
+	# Don't list sysinit actions
+	return 1
+}
+
+bitlbee_start() {
+	su -s /bin/sh -c 'bitlbee -F' bitlbee
+}
+
+dbus_start() {
+	mkdir -p /run/dbus && dbus-uuidgen --ensure && dbus-daemon --system
+}
+
+dbus_stop() {
+	killall dbus-launch
+	killall dbus-daemon
+	rm /run/dbus/pid
+}
+
+dbus_poll() {
+	test -e /run/dbus/pid
+}
+
+iptables_start() {
+	if [ -f /etc/iptables/iptables.rules ]; then
+		iptables-restore < /etc/iptables/iptables.rules
+	fi
+}
+
+iptables_stop() {
+	for table in $(cat /proc/net/ip_tables_names); do
+		iptables-restore < /var/lib/iptables/empty-"$table".rules
+	done
+}
+
+iptables_poll() {
+	sudo iptables -L -n | grep -m 1 -q '^ACCEPT\|^REJECT' >/dev/null 2>&1
+}
+
+sshd_start() {
+	eval "$(command -v sshd)"  # sshd requires an absolute path, so grab path from command -v
+}
+
+sshd_restart() {
+	# Make sure minirc doesn't hang up when restarting it remotely
+	# TODO: Address "busybox" reference, might not be in PATH
+	busybox setsid sh -c '"$0" stop "$@"; "$0" start "$@"' "$0" "$@"
+}
+
+privocy_start() {
+	privoxy --user privoxy.privoxy /etc/privoxy/config
+}
+
+polipo_start() {
+	su -c 'polipo daemonise=true logFile="/var/log/polipo.log"' -s /bin/sh - nobody
+}
+
+dhcpd_start() {
+	if ip link | grep -Fq ${NETWORK_INTERFACE}; then :; else
+		echo_color 3 "waiting for ${NETWORK_INTERFACE} to settle..."
+		wait_on "ip link | grep -Fq ${NETWORK_INTERFACE}"
+	fi
+	# TODO: This doesn't work on nixos, no /etc/dhcpcd.conf, the config file path is hardcoded into systemd service file (wtf!)
+	dhcpcd -nqb
+}
+
+vsftpd_start() {
+	vsftpd &
+}
+
+lighttpd_start() {
+	lighttpd -f /etc/lighttpd/lighttpd.conf
+}
+
+ntpd_start() {
+	ntpd -g -u ntp
+}
+
+wpa_supplicant_start() {
+	wait_on "iwconfig ${WIFI_INTERFACE}"
+	wpa_supplicant -Dwext -B -i"${WIFI_INTERFACE}" -c/etc/wpa_supplicant.conf
+}
+
+icecast_start() {
+	icecast -b -c /etc/icecast.xml
 }
 
 echo_color() {
@@ -234,37 +354,8 @@ echo_color() {
 	printf "\033[1;3%sm%s\033[00m\n" "${color}" "$*"
 }
 
-# handle arguments
-case "$1" in
-init)
-	on_boot;;
-shutdown)
-	on_shutdown;;
-start|stop|restart)
-	cmd="$1"
-	shift
-	for dmn in ${@:-$DAEMONS}; do
-		custom_"${cmd}" "$dmn"
-	done;;
-''|list)
-	# list all daemons and their status
-	for dmn in ${DAEMONS}; do
-		if custom_poll "${dmn}" >/dev/null 2>&1; then
-			echo_color 2 [X] "${dmn}"
-		else
-			echo_color 0 [ ] "${dmn}"
-		fi
-	done;;
---version)
-	echo minirc 0.2;;
-*)
-	self=$(basename "$0")
-	echo "Usage: ${self} [--help] [--version] <action> [list of daemons]"
-	echo
-	echo "Actions:"
-	echo "   ${self} list               shows status of all daemons (default action)"
-	echo "   ${self} start [daemons]    starts daemons"
-	echo "   ${self} stop [daemons]     stops daemons"
-	echo "   ${self} restart [daemons]  restarts daemons";;
-esac
+if [ -r /etc/minirc.conf ]; then
+	. /etc/minirc.conf
+fi
 
+main $@
